name: snacknload
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:




screenshots:
  - description: 'This is shows the loader.'
    path: screenshots/loader.png
  - description: 'This is shows the complete package feature.'
    path: screenshots/snacknload.gif


topics:
  - progress-loader
  - snackbar-flush-bar
  - toast-top-bottom-center
  - adaptive-dialog
  - show-error-success-warning
