name: snacknload
description: SnackNLoad is a Flutter package for customizable loading indicators and top snackbars, making it easy to manage loading states and show success, error, or info messages.
version: 1.0.5
homepage: https://github.com/subhashDev11/snacknload.git
#authors:
#  - Subhash Chandra Shukla (subhashchandras7318@gmail.com)

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

screenshots:
  - description: 'This is shows the loader.'
    path: screenshots/loader.png
  - description: 'This is shows the complete package feature.'
    path: screenshots/snacknload.gif


topics:
  - progress-loader
  - snackbar-flush-bar
  - toast-top-bottom-center
  - adaptive-dialog
  - show-error-success-warning
